version: '3.8'

services:
  scanner:
    build: .
    container_name: permit_scanner
    command: python Main.py
    restart: always
    env_file:
      - .env

  api:
    build: .
    container_name: permit_api
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
  
  db:
    image: postgres:15
    container_name: permit_postgres
    environment:
      POSTGRES_DB: permitdb
      POSTGRES_USER: permituser
      POSTGRES_PASSWORD: permitpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
